### ISSUE TITLE
TurboGrafx-16 Doesn't Work

### ISSUE THREAD

**Issue by davideo7** [ethanaobrien/emuserver#21]
It's listed as one of the systems that supports netplay, but the netplay for this system doesn't work.

This is what I get when I go to create a room:
![image](https://user-images.githubusercontent.com/29381030/177419646-946b3324-60df-45c0-aa65-4fa0eb0ac33c.png)

The room never gets created.

**Comment by ethanaobrien** [comment]
See https://github.com/ethanaobrien/emulatorjs/issues/69
