### ISSUE TITLE
NPM error message when trying to install EmuServer

### ISSUE THREAD

**Issue by shaylevary** [ethanaobrien/emuserver#22]
Hi,

I've tried to install the EmuServer - but keep getting this error message:
npm ERR! notarget No matching version found for engine.io@~4.4.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

I didn't find any documentation on the net regarding this error message - except this one:
https://stackoverflow.com/questions/44331005/npm-error-no-matching-version-found-for

But none of the solutions works.

**Comment by allancoding** [comment]
Can you list here the steps you did?

**Comment by shaylevary** [comment]
Hi,

I've changed the engine.io version inside the package file to a bit older
version, because the engine.io version you've set on your code (4.4.5)
doesn't exist.
After doing it, I've succeed on installing the emuserver.

Now I'm trying to run the emuserver in https, so it will work with my site
(currently It blocks the server because it runs in http mixed content).


Btw, can you please help me with the code that I need to add in order to
set the shader in the localstorage?


Thank you.

בתאריך יום ו׳, 15 ביולי 2022, 18:05, מאת Allan Niles ‏<
***@***.***>:

**Comment by allancoding** [comment]
@ethanaobrien The engine.io package may need to be updated. I found it was with a old unsupported version of socket.io.

**Comment by shaylevary** [comment]
> @ethanaobrien The engine.io package may need to be updated. I found it was with a old unsupported version of socket.io.
I will really appreciate if you'll update the code when you'll have time.

> @shaylevary It may be easier for you to use heroku to host the server over https.

I know, vizzed.com is using the heroku servers, but I prefer to store it on my personal server, so I ask my server admin to set the emuserver under https. I will update if I will still encounter with a problem.

 Another thing, I know it's not right project, but I will really appreciate your help with the localstorage code.

**Comment by allancoding** [comment]
@shaylevary what is the link to the other issue or the name of the issue.

**Comment by shaylevary** [comment]
> @shaylevary what is the link to the other issue or the name of the issue.

Here is the link:
https://github.com/ethanaobrien/emulatorjs/issues/290#issue-1301871821

Thank you.
