### ISSUE TITLE
Testing the server

### ISSUE THREAD

**Issue by allancoding** [ethanaobrien/emuserver#7]
I get this error in the console:
````
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getUrls')
    at (index):26:37
/favicon.ico:1          Failed to load resource: the server responded with a status of 404 ()
(index):19 Uncaught TypeError: Cannot read properties of undefined (reading 'start')
    at HTMLButtonElement.<anonymous> ((index):19:55)
````
[https://emulatorjs.allancoding.ga/](https://emulatorjs.allancoding.ga/)
And I can not get the server to start.

**Comment by ethanaobrien** [comment]
This is strange. do you think you might be able to look into it a bit? I've been trying to work on the next version of emulatorjs

**Comment by allancoding** [comment]
I have a question is the server supposed to start automatically?

**Comment by ethanaobrien** [comment]
No, it is not

**Comment by allancoding** [comment]
This problem was fixed the the newest update.
